"""
Django settings for hhsc2019 project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
import re

IGNORABLE_404_URLS = [
   re.compile(r'^/apple-touch-icon.*\.png$'),
   re.compile(r'^/favicon.ico$'),
   re.compile(r'^/robots.txt$'),
   re.compile(r'^/phpmyadmin/'),
   re.compile(r'\.(cgi|php|pl)$'),
]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(sb2a_kn#vzawax$(txs9wvw%d841hu*1)d(ts4-79=5i)@pv#'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = False

ALLOWED_HOSTS = ['*']
# ALLOWED_HOSTS = ['dreammaxinn.com', 'www.dreammaxinn.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'shops',
    'adminsApi',
    'merchant',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'jwtMiddleware.MD1',
]

ROOT_URLCONF = 'hhsc2019.urls'

#--------------------------数据库连接池
import pymysql
from pymysql.cursors import DictCursor

pymysql.install_as_MySQLdb()
from DBUtils.PooledDB import PooledDB

from base import config


pool = PooledDB(creator=pymysql, 
                mincached=1, 
                maxcached=100, 
                host=config.DBHOST, 
                port=config.DBPORT,
                user=config.DBUSER, 
                passwd=config.DBPASSWD, 
                db=config.DB, 
                charset=config.DBCHAR,
                cursorclass=DictCursor)
print('开启连接池')
#--------------------------------------

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hhsc2019.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

#项目数据库以及相关配置

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://129.211.136.124:6379/6",
        'TIMEOUT': 5,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PASSWORD": ""
        }
    }
}

#SESSION的相关配置
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'
# 设置session失效时间,单位为秒
SESSION_COOKIE_AGE = 60 * 120

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/






USE_TZ = True
#USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/


CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_WHITELIST = ( '*' )

CORS_ALLOW_METHODS = (
        'DELETE',
        'GET',
        'OPTIONS',
        'PATCH',
        'POST',
        'PUT',
        'VIEW',
)

CORS_ALLOW_HEADERS = (
        'XMLHttpRequest',
        'X_FILENAME',
        'accept-encoding',
        'authorization',
        'content-type',
        'dnt',
        'origin',
        'user-agent',
        'x-csrftoken',
        'x-requested-with',
        'token',
)


#TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

STATIC_URL = '/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'statics'),
]

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'


